### ISSUE TITLE
Evaluation based on SPLADE++ ED on dl21 and dl22

### ISSUE THREAD

**Issue by melonking32** [castorini/rank_llm#100]
<img width="573" alt="image" src="https://github.com/castorini/rank_llm/assets/51854482/6974ee61-d91c-4eb7-84ba-4ad24c16883a">

**Comment by melonking32** [comment]
Is it currently not supported to evaluate based on SPLADE++ ED on dl21 and dl22？
How were the results reported in RankZepher obtained？
<img width="493" alt="image" src="https://github.com/castorini/rank_llm/assets/51854482/b0062c4e-83a9-4170-aaa7-555c0f326208">

**Comment by ronakice** [comment]
Hey @melonking32 thanks for your interest. 

Prebuilt index of SPLADE++ ED for MS MARCO v2 (dl21/22) was not yet provided in pyserini at the time of RankZephyr. I built the indexes myself in Anserini, cached the results `https://github.com/castorini/rank_llm_data/tree/main/retrieve_results/SPLADE_P_P_ENSEMBLE_DISTIL` and moved them over (both files for each of dl21/dl22) to retrieve_results/SPLADE_P_P_ENSEMBLE_DISTIL to automatically hit it. You can just copy these files over to achieve similar results. We plan to make this automatic, it is the high priority PR so when that's sorted, you can automatically get the cache when exists. In the meantime, we will also try to add more pyserini indexes. But if you need this quick, reuse the cache :)

**Comment by melonking32** [comment]
Thank you for your reply! I can now read directly from the file. 
I have another question, does the current code not support dl22 evaluation?
![image](https://github.com/castorini/rank_llm/assets/51854482/ec223f15-38c2-4eba-9e8e-9e9c9fb5bc99)

**Comment by ronakice** [comment]
The QRELS were not added to pyserini during RankZephyr's time so that would fail, you can just score them with trec_eval, it still will reorder the results
