### ISSUE TITLE
typo & bug

### ISSUE THREAD

**Issue by MXueguang** [castorini/rank_llm#115]
1. https://github.com/castorini/rank_llm/blob/d62d111784db4fea4312ca2a9941b91be80d057e/src/rank_llm/retrieve_and_rerank.py#L121

2. 
https://github.com/castorini/rank_llm/blob/d62d111784db4fea4312ca2a9941b91be80d057e/src/rank_llm/retrieve_and_rerank.py#L82C35-L82C48

**Comment by sahel-sh** [comment]
Thank you Xueguang for filing this issue. We have made a lot of changes to the rankllm repo including fixing the typo in the function name. Would you please check the main branch, and if the bug is still present, elaborate on that?
