### ISSUE TITLE
Training data of RankZephyr

### ISSUE THREAD

**Issue by liuqi6777** [castorini/rank_llm#120]
Hi, I noticed that you released training data of RankZephyr on huggingface: [https://huggingface.co/datasets/castorini/rank_zephyr_training_data](https://huggingface.co/datasets/castorini/rank_zephyr_training_data). I'd like to ask if it's the dataset described in Section 3.2 of the RankZephyr paper?

**Comment by ronakice** [comment]
Yes this is the data :) Let us know if you need any specific details!
