### ISSUE TITLE
Training set

### ISSUE THREAD

**Issue by Jinhyeong-Lim** [castorini/rank_llm#21]
Hi, thanks for your outstanding work!

Can you share the RankGPT3.5 generated training set you mentioned in the paper?

Thank you

**Comment by ronakice** [comment]
Hey @Jinhyeong-Lim - the training set is the one generated by RankGPT which you can find [here](https://github.com/sunnweiwei/RankGPT). We'll add more instructions shortly!

**Comment by davidmrau** [comment]
Thanks again for the great work. Could you also release the 5k GPT-4 Training examples which would help reproducing your work.
