### ISSUE TITLE
about run_rank_llm.py

### ISSUE THREAD

**Issue by wsa-dhu** [castorini/rank_llm#28]
Why does the error "Unable to find javac" when I run the code？

**Comment by ronakice** [comment]
Can you provide more details? 

This is perhaps something to do with the anserini/pyserini side of things for retrieval. I suggest moving the same issue over there if you are still facing it.

**Comment by ronakice** [comment]
@wsa-dhu can you confirm this is still an issue? Else I'll resolve it

**Comment by susnato** [comment]
Hi @wsa-dhu,

I was facing the same issue and it is caused because you might not have the java compiler installed in your environment.

If you are on Ubuntu then running this might fix the error - 

```bash
sudo apt install default-jdk
```
