### ISSUE TITLE
P1-add docstrings for public functions

### ISSUE THREAD

**Issue by sahel-sh** [castorini/rank_llm#36]

**Comment by AndreSlavescu** [comment]
Interested

**Comment by sahel-sh** [comment]
@AndreSlavescu it's yours

**Comment by sahel-sh** [comment]
@AndreSlavescu would you please add docstrings for public methods in `trec_eval.py` and `response_analysis_verbose.py` as well. This should be much less that what you already worked on for retrieve and rerank

**Comment by sahel-sh** [comment]
PR https://github.com/castorini/rank_llm/pull/75 addresses comment 3
