### ISSUE TITLE
P1-add tests

### ISSUE THREAD

**Issue by sahel-sh** [castorini/rank_llm#37]

**Comment by sahel-sh** [comment]
Adding some basic test for each module would make the code look more polished, with the obvious bonus of catching errors/regressions.
Add a `tests` folder as a sibling to `src` to contain the tests.

**Comment by sahel-sh** [comment]
Classes that need coverage are in the following folder s:
-retrieve
-rerank

**Comment by Richard5678** [comment]
working on this

**Comment by sahel-sh** [comment]
Thank you @Richard5678 for working on this!
