### ISSUE TITLE
P1-pyserini retriever should suppport custom index dir

### ISSUE THREAD

**Issue by sahel-sh** [castorini/rank_llm#38]
The pyserini retriever currently supports dataset names only, we should add support for retrieval with custom prebuild indexes

**Comment by sahel-sh** [comment]
@jasper-xian is working on this

**Comment by jasper-xian** [comment]
@ronakice if we want to support custom user indices, wouldn't we also need the user to provide their own topics files and qrels? 

I can hack around this (kind of) by having the user give pyserini prebuilt topics, but if they give a custom topics file we'd need them to provide qrels too no?

**Comment by ronakice** [comment]
qrels are not necessary, topics yes, if it is custom something like a simple TSV loader. It would be nicer if there is some interaction with pyserini and being able to automatically include all topics/qrels pyserini has support for!

**Comment by ronakice** [comment]
@sahel-sh what do you think?

**Comment by sahel-sh** [comment]
I think there is value in supporting Pyserini with custom index, but we should try to keep it simple. If the topics and index dirs are needed lets ask the user to provide them and qrel as optional for evaluation.
Our code supports ranking hits/results stored in a file, so users always have the option of whatever they want from pyserini and then calling rerank only.

**Comment by sahel-sh** [comment]
Thank you Jasper for working on this issue!
