### ISSUE TITLE
P1-separate scripts from packages

### ISSUE THREAD

**Issue by sahel-sh** [castorini/rank_llm#40]
several modules/files have both classes and main(), the main part should be split into a script file under `script`

**Comment by wu-ming233** [comment]
I currently see:
- `src/rank_llm/retrieve/pyserini_retriever.py`
- several files under `src/rank_llm/analysis`
- `src/rank_llm/evaluation/trec_eval.py`

with both classes and a `main()`. Are these all the intended files?

**Comment by sahel-sh** [comment]
Yes, any file that has a class and a main.

 For all separation, the script should go under scripts with a similar name, like pyerini_retriver  will have a script named run_pyserini_retriver unders scripts/ folder

**Comment by sahel-sh** [comment]
@richard5678 has taken this issue

**Comment by Richard5678** [comment]
I am working on it

**Comment by sahel-sh** [comment]
Thank you @Richard5678 for letting this go to your colleague. Assigning to @wu-ming233 since he has completed the work

**Comment by sahel-sh** [comment]
Thank you @wu-ming233 for working on this
