### ISSUE TITLE
P2- Add variable window size support to rank_gpt class

### ISSUE THREAD

**Issue by sahel-sh** [castorini/rank_llm#43]
Currently only rank_listwise_os_llm.py supports variable window sizes. We should add this to rank_gpt as well.

**Comment by sahel-sh** [comment]
`RankListwiseOSLLM` uses the window size to have a better estimate of the number of output tokens which is in turn needed to determine the amount of  passage truncation during prompt generation. We can change the RankGPT class to do the same. However the original implementation of rankgput does not have this feature and given that the GPT3.5 and GPT4 responses are not always in the requested format, this won't be an accurate estimate anyways.

**Comment by AndreSlavescu** [comment]
Working on this!

**Comment by sahel-sh** [comment]
@AndreSlavescu thank you for working on this so quickly, I think we can mark this issue as fixed now. Would you please confirm?

**Comment by AndreSlavescu** [comment]
Yes, it can be marked as complete.
