### ISSUE TITLE
p1- Update demo scripts

### ISSUE THREAD

**Issue by sahel-sh** [castorini/rank_llm#71]
1- Use ResultsWriter in the existing demos to write the output in three different formats (sorted hits in json format, output in trec eval format, and the ranking execution summary in json format)
2- rankGPT demo: Add a demo for creating a rankGPT agent, then create a reranker using the agent, call rerank, and write results, no need to populate parameters with default values, the demo should look as simple as possible.

**Comment by yilinjz** [comment]
@sahel-sh Can I take this as well? Seems similar to what I did in a previous PR.

**Comment by sahel-sh** [comment]
@yilinjz it is yours

**Comment by sahel-sh** [comment]
Thank you @yilinjz for working on this!
