### ISSUE TITLE
p1- response analysis and evaluation should work with the rerank results

### ISSUE THREAD

**Issue by sahel-sh** [castorini/rank_llm#77]
both response analysis and evaluation classes, take files as input.
This means the user need to write the rerank results using resultsWriter after reranking, then call these modules with the newly created files. We should add the capability to the two classes to work with list[Result] as an alternative input format.

**Comment by AndreSlavescu** [comment]
interested

**Comment by sahel-sh** [comment]
PR https://github.com/castorini/rank_llm/pull/87 fixes the issue.
@AndreSlavescu thank you for working on this!
