### ISSUE TITLE
p2- expose pyserini retriever's top k candidate to retriever with k=100 being the default value

### ISSUE THREAD

**Issue by sahel-sh** [castorini/rank_llm#81]
Currently, retriever.from_.. for dataset and custom index does not take k as a parameter, they should be able to take it and pass it down to pyserini.
The candidate file names used for storing and reusing the retrieved_results should also have this parameter included, so that retrieving top 20 does not create a false collision with retriving top 100 by having the same file name.

**Comment by sahel-sh** [comment]
@jasper-xian given your previous cl about pyserini_retriever, you are a good candidate for this change which would be much simpler. Do you have the bandwidth to work on this?

**Comment by jasper-xian** [comment]
yup I can take this

**Comment by sahel-sh** [comment]
it is yours, thank you!

**Comment by sahel-sh** [comment]
Thank you @jasper-xian for working on this!
